services:
    prefixed.manager:
        class: imkingdavid\prefixed\core\manager
        arguments:
            - @dbal.conn
            - @cache.driver
            - @template
            - @request
