services:
    prefixed.manager:
        class: phpbb_ext_imkingdavid_prefixed_core_manager
        arguments:
            - @dbal.conn
            - @cache.driver
            - @template
            - @request
